# https://taskfile.dev/usage/
version: '3'
tasks:
  default: bun run test
  dev: bun run dev
  repl: bun repl

  books: |
    curl -v -H "Authorization: Bearer dogoodjob" http://localhost:3000/books?pageSize=3 | jq
  books-hi: |
    curl -v -H "Authorization: Bearer dogoodjob" http://localhost:3000/books/hi | jq
  book-post: |
    # curl -X POST http://localhost:3000/isbn/9787115424914
    curl -X POST http://localhost:3000/books/isbn/9787030758880

  ## bun prod
  prod: |
    bun run build
    bun run dist/index.js

  ## Fly.io
  f-who: fly auth whoami
  f-dep: fly deploy --verbose

  ## Cloudflare workers
  cf-dev: bun run cf-dev
  cf: task cf-dev
  dep: bun run cf-dep
  open: open https://notion-data-helper.shareup.workers.dev
  secrets: |
    bunx wrangler secret list
    # bunx wrangler secret put BEARER_AUTH_TOKEN

  ## Tools
  ping: curl -v http://localhost:3000/ping | jq
  timing: curl -v http://localhost:3000/timing?delay=6 | jq
  test-env: |
    curl http://localhost:3000/envs
    curl -H "Authorization: Bearer dogoodjob" http://localhost:3000/envs | jq
  envs: 
    silent: true
    cmds: 
    - bun --print process.env
  gen-uuid: 
    silent: true
    cmds: 
    - bun --print "crypto.randomUUID()"

  setup: |
    bun add @notionhq/client
    
    # use bun env
    # bun install @dotenvx/dotenvx -g