# https://taskfile.dev/usage/
version: '3'

vars:
  TEST_ONLY_ENV: "test only env in Taskfile.yml"
dotenv:
  # first over last? ENV=prod task hi
  - .env.{{.ENV}}
  # - .env.${ENV}
  - .env

tasks:
  default: bun run test
  dev: bun run dev
  repl: bun repl
  rel: |
    bun run test && bun run release
    git push --follow-tags origin main
    
  rel-skip-ci: standard-version --skip.commit

  # env test
  hi: |
    echo "TEST_ONLY_ENV: {{.TEST_ONLY_ENV}}"
    echo "TEST_ONLY_ENV: ${TEST_ONLY_ENV}"

  ## bun prod
  prod: |
    bun run build
    bun run dist/index.js

  books: |
    curl -v -H "Authorization: Bearer {{.BEARER_AUTH_TOKEN}}" {{.API_HOST}}/books?pageSize=3 | jq
  books-hi: |
    curl -v -H "Authorization: Bearer {{.BEARER_AUTH_TOKEN}}" {{.API_HOST}}/books/hi | jq
  fill-books: |
    bin/book export -d 1c4673e59ab681f4b64de4972526a88b 
    sleep 2
    bin/book import db/output/db-1bf673e59ab680e691c1fb7a62646902.json -e db/output/db-1c4673e59ab681f4b64de4972526a88b.json -d 1c4673e59ab681f4b64de4972526a88b

  ## Fly.io
  f-who: fly auth whoami
  f-dep: fly deploy --verbose

  ## Cloudflare workers
  cf-dev: bun run cf-dev
  cf: task cf-dev
  dep: bun run cf-dep
  open: open https://notion-data-helper.shareup.workers.dev
  secrets: |
    bunx wrangler secret list
    # bunx wrangler secret put BEARER_BEARER_AUTH_TOKEN

  ## Tools
  ping: curl -v {{.API_HOST}}/ping | jq
  timing: curl -v {{.API_HOST}}/timing?delay=6 | jq
  test-env: |
    curl {{.API_HOST}}/envs
    curl -H "Authorization: Bearer {{.BEARER_AUTH_TOKEN}}" {{.API_HOST}}/envs | jq
  envs: 
    silent: true
    cmds: 
    - bun --print process.env
  gen-uuid: 
    silent: true
    cmds: 
    - bun --print "crypto.randomUUID()"

  setup: |
    bun add @notionhq/client
    
    # use bun env
    # bun install @dotenvx/dotenvx -g